[package]
name = "openpad-widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
makepad-widgets = { git = "https://github.com/makepad/makepad.git", branch = "dev" }
openpad-protocol = { path = "../openpad-protocol" }
portable-pty = "0.9.0"
hostname = "0.4"
